### ISSUE TITLE
Fix `#LEVELHOLD` behavior for Shoutoku Taiko

### ISSUE THREAD

**Issue by vivaria** [vivaria/tja2fumen#52]
There is a single `#LEVELHOLD` song in all of ESE: Shoutoku Taiko:

```bash
#SECTION
#BRANCHSTART r,5,6
#N
#LEVELHOLD
100000000100000000200000500000000008000000100200,
1000202210201120,
#E
100000000100000000200000500000000008000000100200,
1000202210201120,
#M
100000000100000000200000500000000008000000100200,
1000202210201120,
#SECTION
#BRANCHSTART r,7,8
#BRANCHEND
500000000008000000200200100000200200200200200200,
1010202210201020,
#SECTION
#BRANCHSTART r,4,5
#N
```

I don't really understand how this works yet, so I need to make sure this produces the correct fumen.

**Comment by vivaria** [comment]
There may be some issues with how I parse `#SECTION` here, too. 😓

**Comment by IepIweidieng** [comment]
In TaikoJiro, `#LEVELHOLD` works per-branch and can't be unheld.
https://github.com/IepIweidieng/TJAPlayer3/blob/gh-pages/tja.md#levelhold
