### ISSUE TITLE
SENOTES defects and suggestions for additional features

### ISSUE THREAD

**Issue by Lanthanum-057** [vivaria/tja2fumen#69]
I am Japanese, so I go through a translator.
Please understand that there may be strange English.

(For some reason I could not attach the zip file, so I am attaching it as a txt.)

I have a request for corrections regarding the notes in the file you attached. When I convert the attached file, the first 16 beats are "ドドドド..." but the following 24 beats become "ドコドコ" instead. These 24 beats should actually be "ドドドド..."
Even in sections where the BPM changes and the SCROLL becomes 0.56 or 0.67, it still becomes "ドコドコ..." It should also be "ドドドド..." in these sections.

Additionally, I would like to request the addition of a command to change the notes to any desired characters. Here's an example:

d = ド
o = コ
dn = ドン
ka = カッ
k = カ

dodn = ドコドン
dddn = ドドドン
kkka = カカカッ

By adding this functionality, it would allow for the creation of a flexible custom fumen. I would greatly appreciate it if you could consider implementing these changes.

[senotes_test.txt](https://github.com/vivaria/tja2fumen/files/14202119/senotes_test.txt)

**Comment by vivaria** [comment]
Thank you so much for requesting this feature! ❤️ 

((No worries about Japanese/English translator -- I do the same thing when reading Japanese Taiko sites 😆))

----

> I have a request for corrections regarding the notes in the file you attached. When I convert the attached file, the first 16 beats are "ドドドド..." but the following 24 beats become "ドコドコ" instead. These 24 beats should actually be "ドドドド..."

Thank you for `senotes_test.txt` -- I will try to test this file, and try to fix the bug. :)

----

> Additionally, I would like to request the addition of a command to change the notes to any desired characters. Here's an example:
> 
> d = ド o = コ dn = ドン ka = カッ k = カ

This would be very good! (only having `1` and `2` = d/k has made things hard for me.)

I think I could add this feature to the code very easily. Here are the relevant lines of code:

https://github.com/vivaria/tja2fumen/blob/5474ad0baa698669912600b1d32abb1bc0466353/src/tja2fumen/constants.py#L8-L14

https://github.com/vivaria/tja2fumen/blob/5474ad0baa698669912600b1d32abb1bc0466353/src/tja2fumen/constants.py#L31-L37

It might be easier to only have 1 letter/character per note (dn -> n, ka -> t)? So all together:

> d = ド 
> o = コ 
> n = ドン 
> t = カッ 
> k = カ

```diff
 TJA_NOTE_TYPES = { 
     '0': 'Blank',
     '1': 'Don',
+    'n': 'Don',   # ドン (do~n -> 'n')
+    'd': 'Don2',  # ド (do -> 'd') 
+    'o': 'Don3',  # コ (ko -> 'o')
     '2': 'Ka',
+    't': 'Ka',    # カッ (ka~tsu -> 't')
+    'k': 'Ka2',   # カ (ka -> 'k') 
     '3': 'DON', 
     '4': 'KA',
```

Would this be okay? Or is it too confusing?

**Comment by Lanthanum-057** [comment]
I think it's a really great idea!
It would be much appreciated if you could implement this.

**Comment by sakurada0291** [comment]
> Thank you so much for requesting this feature! ❤️
> 
> ((No worries about Japanese/English translator -- I do the same thing when reading Japanese Taiko sites 😆))
> 
> > I have a request for corrections regarding the notes in the file you attached. When I convert the attached file, the first 16 beats are "ドドドド..." but the following 24 beats become "ドコドコ" instead. These 24 beats should actually be "ドドドド..."
> 
> Thank you for `senotes_test.txt` -- I will try to test this file, and try to fix the bug. :)
> 
> > Additionally, I would like to request the addition of a command to change the notes to any desired characters. Here's an example:
> > d = ド o = コ dn = ドン ka = カッ k = カ
> 
> This would be very good! (TJAs only having `1` and `2` = d/k has made things hard for me 😓.)
> 
> I think I could add this feature to the code very easily. Here are the relevant lines of code:
> 
> https://github.com/vivaria/tja2fumen/blob/5474ad0baa698669912600b1d32abb1bc0466353/src/tja2fumen/constants.py#L8-L14
> 
> https://github.com/vivaria/tja2fumen/blob/5474ad0baa698669912600b1d32abb1bc0466353/src/tja2fumen/constants.py#L31-L37
> 
> It might be easier to only have 1 letter/character per note (dn -> n, ka -> t)? So all together:
> 
> > d = ド
> > o = コ
> > n = ドン
> > t = カッ
> > k = カ
> 
> ```diff
>  TJA_NOTE_TYPES = { 
>      '0': 'Blank',
>      '1': 'Don',
> +    'n': 'Don',   # ドン (do~n -> 'n')
> +    'd': 'Don2',  # ド (do -> 'd') 
> +    'o': 'Don3',  # コ (ko -> 'o')
>      '2': 'Ka',
> +    't': 'Ka',    # カッ (ka~tsu -> 't')
> +    'k': 'Ka2',   # カ (ka -> 'k') 
>      '3': 'DON', 
>      '4': 'KA',
> ```
> 
> Would this be okay? Or is it too confusing?

I would like to oppose the idea since there is a command that you have not yet acknowledged, but my suggestion will go for plan B if this kind of text doesn't work.

**Comment by IepIweidieng** [comment]
> There is a new command that is required to convert it into a .bin file, and it's called `#SENOTECHANGE`.
> [...]
> However, there is no `1` and `0` in `#SENOTECHANGE` command.
> 
> Reference: https://iepiweidieng.github.io/TJAPlayer3/TJAPlayer3-AioiLight-docs/doc/tja

There are actually `1` to `5` for `#SENOTECHANGE` but just not fully mentioned in the example.

https://github.com/IepIweidieng/TJAPlayer3/blob/gh-pages/tja.md#senotechange

TJAPlayer3 implementation references:

* Parsing of `#SENOTECHANGE`: https://github.com/AioiLight/TJAPlayer3/blob/ver-1.6.x/TJAPlayer3/Songs/CDTX.cs#L3867-L3871
* `#SENOTECHANGE` sets `CChip.nSenote` to *the `#SENOTECHANGE` value − 1*, but `CChip.nSenote` is later overridden for note types other than small Don (`1`) and small Katsu (`2`): https://github.com/AioiLight/TJAPlayer3/blob/ver-1.6.x/TJAPlayer3/Songs/CDTX.cs#L4177-L4214
* `CChip.nSenote` works by being used for calculating the coordination of the SENOTES sprite map, so `1` through `5` for `#SENOTECHANGE` represent respectively <ruby>ド<rt>do</rt>ン<rt>n</rt></ruby>, <ruby>ド<rt>do</rt></ruby>, <ruby>コ<rt>ko</rt></ruby>, <ruby>カッ<rt>ka'</rt></ruby>, & <ruby>カ<rt>ka</rt></ruby>:
  ![](https://github.com/AioiLight/TJAPlayer3/blob/ver-1.6.x/Test/System/SimpleStyle/Graphics/5_Game/SENotes.png?raw=true)

**Comment by sakurada0291** [comment]
> > There is a new command that is required to convert it into a .bin file, and it's called `#SENOTECHANGE`.
> > [...]
> > However, there is no `1` and `0` in `#SENOTECHANGE` command.
> > Reference: https://iepiweidieng.github.io/TJAPlayer3/TJAPlayer3-AioiLight-docs/doc/tja
> 
> There are actually `1` to `5` for `#SENOTECHANGE` but just not fully mentioned in the example.
> 
> https://github.com/IepIweidieng/TJAPlayer3/blob/gh-pages/tja.md#senotechange
> 
> TJAPlayer3 implementation references:
> 
> * Parsing of `#SENOTECHANGE`: https://github.com/AioiLight/TJAPlayer3/blob/ver-1.6.x/TJAPlayer3/Songs/CDTX.cs#L3867-L3871
> * `#SENOTECHANGE` sets `CChip.nSenote` to _the `#SENOTECHANGE` value − 1_, but `CChip.nSenote` is later overridden for note types other than small Don (`1`) and small Katsu (`2`): https://github.com/AioiLight/TJAPlayer3/blob/ver-1.6.x/TJAPlayer3/Songs/CDTX.cs#L4177-L4214
> * `CChip.nSenote` works by being used for calculating the coordination of the SENOTES sprite map, so `1` through `5` for `#SENOTECHANGE` represent respectively ドdoンn, ドdo, コko, カッka', & カka:
>   ![](https://github.com/AioiLight/TJAPlayer3/blob/ver-1.6.x/Test/System/SimpleStyle/Graphics/5_Game/SENotes.png?raw=true)

Ahh, that one. I didn't know there's more values for these.

**Comment by vivaria** [comment]
Very very sorry for the long delay on this issue. I plan to return to `tja2fumen` development in October. I will try to fix this issue soon (as well as some other pending issues that were recently reported to me).

Thank you for your patience. :hearts:

**Comment by vivaria** [comment]
@Lanthanum-057 @sakurada0291 I have created a "testing" release to add support for `#SENOTECHANGE`. If you could please test to make sure it works for your needs: https://github.com/vivaria/tja2fumen/releases/tag/0.9.0.dev0

If it works I will then go and make the proper v0.9.0 release.

**Comment by sakurada0291** [comment]
👌
