### ISSUE TITLE
Misalignment of notes

### ISSUE THREAD

**Issue by Lanthanum-057** [vivaria/tja2fumen#71]
I don't know the exact cause, but the notes are shifting more and more as time goes on.
The attached images are the part at the beginning and end of the performance.
The upper part of the image is the fumen converted using tja2fumen and the lower part is the original fumen.
![Start00](https://github.com/vivaria/tja2fumen/assets/159145693/ceeb6200-cf47-4481-b4d8-1617e6daede8)
![End00](https://github.com/vivaria/tja2fumen/assets/159145693/8771363b-b0c8-4a16-9189-ebdfd20da62b)

**Comment by vivaria** [comment]
Thank you so much for reporting this issue! Could you share the TJA file so that I could test?

**Comment by Lanthanum-057** [comment]
I forgot to attach the TJA file. Sorry.
[ssnrns_x.txt](https://github.com/vivaria/tja2fumen/files/14397521/ssnrns_x.txt)

**Comment by vivaria** [comment]
Ahhh, this is RNG Cinderella! This is perfect, it allows me to write a new test using the official fumen. 😊 

I will get this done by tonight. (Sorry for the delay! I have been sick... 😷)

**Comment by vivaria** [comment]
Hrmm. I am a bit confused. When I compare the TJA file to my copy of the official fumen, everything matches 100%.

Converted TJA:

![image](https://github.com/vivaria/tja2fumen/assets/76574898/45ffb245-69ea-48ff-bd83-f5b2a25e00ab)

![image](https://github.com/vivaria/tja2fumen/assets/76574898/848f2a88-9077-4f6e-a83e-c9777198b446)

Fumen:

![image](https://github.com/vivaria/tja2fumen/assets/76574898/6518d658-5fb4-449f-a9f6-cdc3156bf3c4)

![image](https://github.com/vivaria/tja2fumen/assets/76574898/55014f51-c744-44e4-99fc-65281cb5ca38)

Here is the official fumen (NS2) that I am testing against: [ssnrns.zip](https://github.com/vivaria/tja2fumen/files/14471526/ssnrns.zip)

Could you please share the official fumen are you comparing with? (I want to check to see if it is the same official fumen I have.)

**Comment by Lanthanum-057** [comment]
My apologies. I just converted it again and played it back at the same time and it matched perfectly.
I converted the same TJA, but maybe there was some kind of bug only then.
Sorry for the trouble.

**Comment by vivaria** [comment]
No need to say sorry!! Your issues are still very good and helpful -- it is always good for me to double check and make sure everything is working 100%. ♥️ ♥️ 

Thank you for reporting anyway, and I hope that you will continue to open issues whenever something goes wrong. ❤️
