### ISSUE TITLE
TakoTako incorrectly creates a `data.json` file with Variety (genreNo 3) by default

### ISSUE THREAD

**Issue by asmodyte** [vivaria/tja2fumen#78]
Title is self explanatory. Trying to convert songs from ESE causes all the songs to be grouped into 1 genre (genre 3 aka Vocaloid) instead of being put in the correct genre.
example:
![Screenshot 2024-09-16 085616](https://github.com/user-attachments/assets/224f8a3e-4703-4df6-9840-f9faac968f0a)

**Comment by vivaria** [comment]
Thank you for reporting! This is outside of `tja2fumen`'s control. The `data.json` file is created by TakoTako code. What TakoTako does is look for specific Japanese strings, and if it doesn't find them, it returns 3 (which is actually Variety) by default. See this section of code: https://github.com/Fluto/TakoTako/blob/c269bcab60530877a16c2a473c84796b94d0a5ce/TJAConvert/TJAMetaData.cs#L237-L264

So, I would suggest reporting to the TakoTako repo instead: https://github.com/Fluto/TakoTako

Closing.
